# Generated by Django 5.1.7 on 2025-06-07 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee ID for the teacher', max_length=20, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text="Teacher's contact phone number", max_length=15, null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='The academic branch this teacher belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='student.branch')),
                ('user', models.OneToOneField(help_text='Django User account associated with this teacher', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
