# Generated by Django 5.1.7 on 2025-06-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_offered', to='student.academic')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='student.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='student.course')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., A, B, C, D', max_length=10)),
                ('academic', models.ForeignKey(help_text='The academic year this division is for', on_delete=django.db.models.deletion.CASCADE, related_name='divisions_in_year', to='student.academic')),
                ('branch', models.ForeignKey(help_text='The branch this division belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='student.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.CharField(choices=[('1st', 'Semester 1'), ('2nd', 'Semester 2'), ('3rd', 'Semester 3'), ('4th', 'Semester 4'), ('5th', 'Semester 5'), ('6th', 'Semester 6'), ('7th', 'Semester 7'), ('8th', 'Semester 8')], help_text='e.g., 1st, 2nd, 3rd, 4th, 5th, 6th, 7th, 8th', max_length=5)),
                ('academic', models.ForeignKey(help_text='Academic year this semester belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='student.academic')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(help_text='The semester in which this course is typically offered', on_delete=django.db.models.deletion.CASCADE, related_name='courses_offered', to='student.semester'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('prn', models.BigIntegerField(default=None)),
                ('academic', models.ForeignKey(blank=True, help_text="Choose the student's current academic year", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_year', to='student.academic')),
                ('branch', models.ForeignKey(blank=True, help_text="choose the student's branch", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_branch', to='student.branch')),
                ('division', models.ForeignKey(blank=True, help_text="The student's assigned division", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_division', to='student.division')),
                ('semester', models.ForeignKey(blank=True, help_text="The student's current academic semester", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_semester', to='student.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_letter', models.CharField(blank=True, max_length=5, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_received', to='student.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students_enrolled',
            field=models.ManyToManyField(blank=True, related_name='enrolled_course', to='student.student'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_taken', to='student.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='student.student')),
            ],
        ),
    ]
