# Generated by Django 5.1.7 on 2025-06-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students_enrolled',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to='student.student'),
        ),
    ]
